### ISSUE TITLE
魔改X-ui能否添加SS 2022支持？

### ISSUE THREAD

**Issue by jrnick7** [Misaka-blog/x-ui#15]
官方版迟迟不更新对新的加密方式的支持（SS-RUST，SS 2022等），魔改版是否可以考虑添加这些新的加密？

**Comment by misakano7545** [comment]
会考虑下

**Comment by misakano7545** [comment]
![image](https://user-images.githubusercontent.com/96560028/174443399-05479f69-e218-4890-8497-d20c7b9bcb69.png)

就目前来看，SS2022貌似改不了，我问下FrankKafkaYu吧

**Comment by misakano7545** [comment]
今日新版本已支持！

**Comment by jrnick7** [comment]
使用2022-blake3-aes-256-gcm的随机密码，xray提示failed to create server > proxy/shadowsocks_2022: create service > bad key，无法正常启动

**Comment by misakano7545** [comment]
这个你看下xray的文档，ss2022对密码长度有要求

Sent from ProtonMail for iOS

在 周日, 6月 19, 2022 在 16:13, jrnick7 ***@***.***> 来信：

**Comment by misakano7545** [comment]
https://xtls.github.io/config/inbounds/shadowsocks.html

**Comment by jrnick7** [comment]
问题解决了，用openssl rand -base64 32生产的密码可以使用，但是xui面板里默认的随机密码不是按照openssl rand -base64 32生成，所以使用不了，不知道能否改变默认随机密码的生成方式，现在是能自行更新密码

**Comment by misakano7545** [comment]
> 问题解决了，用openssl rand -base64 32生产的密码可以使用，但是xui面板里默认的随机密码不是按照openssl rand -base64 32生成，所以使用不了，不知道能否改变默认随机密码的生成方式，现在是能自行更新密码

我在目前的0.3.4.2已经尝试过了，暂时不行

**Comment by LoserFox** [comment]
2022-blake3-aes-128-gcm对密码的要求为任意16位字符串
2022-blake3-aes-256-gcm，2022-blake3-chacha20-poly1305对密码的要求为一个大于32位的base64
我的对此的修复方案：#18
