### ISSUE TITLE
Telegram bot

### ISSUE THREAD

**Issue by Maneeha1234SL** [Misaka-blog/x-ui#25]
🛑Manage commands that can be used by the average person using telegram Bot    and commands that can be used by an administrator

Examples:
Allow the average person to use only the / status command

Then we can allow all people who get v2ray accounts from us to use BOT

Because they can get about their data consumption by starting the bot
Because if telegram allows all people to control the commands of the bot we will have a problem

**Comment by misakano7545** [comment]
@Maneeha1234SL But x-ui panel only designed for personal used
